// Date: 08/09/2013 15:23:17
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelModel extends ModelBase
{
  //fields
    ModelRenderer head;
    ModelRenderer topjaw;
    ModelRenderer leftmouth;
    ModelRenderer rightmouth;
    ModelRenderer bottomjaw;
    ModelRenderer topteeth;
    ModelRenderer bottomteeth;
    ModelRenderer lefthorn01;
    ModelRenderer lefthorn02;
    ModelRenderer lefthorn03;
    ModelRenderer righthorn01;
    ModelRenderer righthorn02;
    ModelRenderer righthorn03;
    ModelRenderer body;
    ModelRenderer leftshoulder;
    ModelRenderer rightshoulder;
    ModelRenderer leftarm;
    ModelRenderer rightarm;
    ModelRenderer leftleg;
    ModelRenderer rightleg;
    ModelRenderer leftlowerleg;
    ModelRenderer rightlowerleg;
    ModelRenderer leftfoot;
    ModelRenderer rightfoot;
  
  public ModelModel()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-5F, -4F, -9F, 10, 11, 9);
      head.setRotationPoint(0F, -4F, -11F);
      head.setTextureSize(128, 64);
      head.mirror = true;
      setRotation(head, 0.7853982F, 0F, 0F);
      topjaw = new ModelRenderer(this, 38, 0);
      topjaw.addBox(-6F, 0F, -12F, 12, 6, 6);
      topjaw.setRotationPoint(0F, -4F, -11F);
      topjaw.setTextureSize(128, 64);
      topjaw.mirror = true;
      setRotation(topjaw, 0.2094395F, 0F, 0F);
      leftmouth = new ModelRenderer(this, 120, 0);
      leftmouth.addBox(4.9F, -2F, -11F, 1, 8, 3);
      leftmouth.setRotationPoint(0F, -4F, -11F);
      leftmouth.setTextureSize(128, 64);
      leftmouth.mirror = true;
      setRotation(leftmouth, 0.7853982F, 0F, 0F);
      rightmouth.mirror = true;
      rightmouth = new ModelRenderer(this, 120, 0);
      rightmouth.addBox(-5.9F, -2F, -11F, 1, 8, 3);
      rightmouth.setRotationPoint(0F, -4F, -11F);
      rightmouth.setTextureSize(128, 64);
      rightmouth.mirror = true;
      setRotation(rightmouth, 0.7853982F, 0F, 0F);
      rightmouth.mirror = false;
      bottomjaw = new ModelRenderer(this, 74, 0);
      bottomjaw.addBox(-6F, 8F, -13F, 12, 4, 12);
      bottomjaw.setRotationPoint(0F, -4F, -11F);
      bottomjaw.setTextureSize(128, 64);
      bottomjaw.mirror = true;
      setRotation(bottomjaw, 0.4537856F, 0F, 0F);
      topteeth = new ModelRenderer(this, 38, 12);
      topteeth.addBox(-5F, 5F, -11F, 10, 3, 0);
      topteeth.setRotationPoint(0F, -4F, -11F);
      topteeth.setTextureSize(128, 64);
      topteeth.mirror = true;
      setRotation(topteeth, 0.2094395F, 0F, 0F);
      bottomteeth = new ModelRenderer(this, 38, 15);
      bottomteeth.addBox(-5F, 5F, -12F, 10, 4, 0);
      bottomteeth.setRotationPoint(0F, -4F, -11F);
      bottomteeth.setTextureSize(128, 64);
      bottomteeth.mirror = true;
      setRotation(bottomteeth, 0.4537856F, 0F, 0F);
      lefthorn01 = new ModelRenderer(this, 110, 17);
      lefthorn01.addBox(5F, -2F, -7F, 4, 4, 3);
      lefthorn01.setRotationPoint(0F, -4F, -11F);
      lefthorn01.setTextureSize(128, 64);
      lefthorn01.mirror = true;
      setRotation(lefthorn01, 0.4537856F, 0F, 0F);
      lefthorn02 = new ModelRenderer(this, 110, 17);
      lefthorn02.addBox(-1F, -2F, -15F, 3, 2, 6);
      lefthorn02.setRotationPoint(0F, -4F, -11F);
      lefthorn02.setTextureSize(128, 64);
      lefthorn02.mirror = true;
      setRotation(lefthorn02, 0.418879F, -0.7853982F, -0.418879F);
      lefthorn03 = new ModelRenderer(this, 110, 17);
      lefthorn03.addBox(13F, -3F, -9F, 2, 2, 7);
      lefthorn03.setRotationPoint(0F, -4F, -11F);
      lefthorn03.setTextureSize(128, 64);
      lefthorn03.mirror = true;
      setRotation(lefthorn03, 0.5585054F, 0.418879F, 0.3490659F);
      righthorn01.mirror = true;
      righthorn01 = new ModelRenderer(this, 110, 17);
      righthorn01.addBox(-9F, -2F, -7F, 4, 4, 3);
      righthorn01.setRotationPoint(0F, -4F, -11F);
      righthorn01.setTextureSize(128, 64);
      righthorn01.mirror = true;
      setRotation(righthorn01, 0.4537856F, 0F, 0F);
      righthorn01.mirror = false;
      righthorn02.mirror = true;
      righthorn02 = new ModelRenderer(this, 110, 17);
      righthorn02.addBox(-2F, -2F, -15F, 3, 2, 6);
      righthorn02.setRotationPoint(0F, -4F, -11F);
      righthorn02.setTextureSize(128, 64);
      righthorn02.mirror = true;
      setRotation(righthorn02, 0.418879F, 0.7853982F, 0.418879F);
      righthorn02.mirror = false;
      righthorn03.mirror = true;
      righthorn03 = new ModelRenderer(this, 110, 17);
      righthorn03.addBox(-15F, -3F, -9F, 2, 2, 7);
      righthorn03.setRotationPoint(0F, -4F, -11F);
      righthorn03.setTextureSize(128, 64);
      righthorn03.mirror = true;
      setRotation(righthorn03, 0.5585054F, -0.418879F, -0.3490659F);
      righthorn03.mirror = false;
      body = new ModelRenderer(this, 0, 20);
      body.addBox(-6F, 0F, -4F, 12, 22, 10);
      body.setRotationPoint(0F, -9F, -12F);
      body.setTextureSize(128, 64);
      body.mirror = true;
      setRotation(body, 0.7853982F, 0F, 0F);
      leftshoulder = new ModelRenderer(this, 44, 20);
      leftshoulder.addBox(6F, 0F, -1F, 5, 6, 6);
      leftshoulder.setRotationPoint(0F, -9F, -12F);
      leftshoulder.setTextureSize(128, 64);
      leftshoulder.mirror = true;
      setRotation(leftshoulder, 0.7853982F, 0F, 0F);
      rightshoulder.mirror = true;
      rightshoulder = new ModelRenderer(this, 44, 20);
      rightshoulder.addBox(-11F, 0F, -1F, 5, 6, 6);
      rightshoulder.setRotationPoint(0F, -9F, -12F);
      rightshoulder.setTextureSize(128, 64);
      rightshoulder.mirror = true;
      setRotation(rightshoulder, 0.7853982F, 0F, 0F);
      rightshoulder.mirror = false;
      leftarm = new ModelRenderer(this, 66, 20);
      leftarm.addBox(-1F, 0F, -2F, 3, 12, 4);
      leftarm.setRotationPoint(8F, -8F, -8F);
      leftarm.setTextureSize(128, 64);
      leftarm.mirror = true;
      setRotation(leftarm, 0F, 0F, 0F);
      rightarm.mirror = true;
      rightarm = new ModelRenderer(this, 66, 20);
      rightarm.addBox(-2F, 0F, -2F, 3, 12, 4);
      rightarm.setRotationPoint(-8F, -8F, -8F);
      rightarm.setTextureSize(128, 64);
      rightarm.mirror = true;
      setRotation(rightarm, 0F, 0F, 0F);
      rightarm.mirror = false;
      leftleg = new ModelRenderer(this, 85, 17);
      leftleg.addBox(-3F, 0F, -3F, 6, 12, 6);
      leftleg.setRotationPoint(8F, 2F, 1F);
      leftleg.setTextureSize(128, 64);
      leftleg.mirror = true;
      setRotation(leftleg, 0.5410521F, 0F, 0F);
      rightleg.mirror = true;
      rightleg = new ModelRenderer(this, 85, 17);
      rightleg.addBox(-3F, 0F, -3F, 6, 12, 6);
      rightleg.setRotationPoint(-8F, 2F, 1F);
      rightleg.setTextureSize(128, 64);
      rightleg.mirror = true;
      setRotation(rightleg, 0.5410521F, 0F, 0F);
      rightleg.mirror = false;
      leftlowerleg = new ModelRenderer(this, 87, 35);
      leftlowerleg.addBox(-2.5F, 4F, 6F, 5, 13, 5);
      leftlowerleg.setRotationPoint(8F, 2F, 1F);
      leftlowerleg.setTextureSize(128, 64);
      leftlowerleg.mirror = true;
      setRotation(leftlowerleg, -0.4886922F, 0F, 0F);
      rightlowerleg.mirror = true;
      rightlowerleg = new ModelRenderer(this, 87, 35);
      rightlowerleg.addBox(-2.5F, 4F, 6F, 5, 13, 5);
      rightlowerleg.setRotationPoint(-8F, 2F, 1F);
      rightlowerleg.setTextureSize(128, 64);
      rightlowerleg.mirror = true;
      setRotation(rightlowerleg, -0.4886922F, 0F, 0F);
      rightlowerleg.mirror = false;
      leftfoot = new ModelRenderer(this, 83, 53);
      leftfoot.addBox(-3.5F, 18F, -4F, 7, 4, 7);
      leftfoot.setRotationPoint(8F, 2F, 1F);
      leftfoot.setTextureSize(128, 64);
      leftfoot.mirror = true;
      setRotation(leftfoot, 0F, 0F, 0F);
      rightfoot.mirror = true;
      rightfoot = new ModelRenderer(this, 83, 53);
      rightfoot.addBox(-3.5F, 18F, -4F, 7, 4, 7);
      rightfoot.setRotationPoint(-8F, 2F, 1F);
      rightfoot.setTextureSize(128, 64);
      rightfoot.mirror = true;
      setRotation(rightfoot, 0F, 0F, 0F);
      rightfoot.mirror = false;
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    head.render(f5);
    topjaw.render(f5);
    leftmouth.render(f5);
    rightmouth.render(f5);
    bottomjaw.render(f5);
    topteeth.render(f5);
    bottomteeth.render(f5);
    lefthorn01.render(f5);
    lefthorn02.render(f5);
    lefthorn03.render(f5);
    righthorn01.render(f5);
    righthorn02.render(f5);
    righthorn03.render(f5);
    body.render(f5);
    leftshoulder.render(f5);
    rightshoulder.render(f5);
    leftarm.render(f5);
    rightarm.render(f5);
    leftleg.render(f5);
    rightleg.render(f5);
    leftlowerleg.render(f5);
    rightlowerleg.render(f5);
    leftfoot.render(f5);
    rightfoot.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
